### ISSUE TITLE
erreur à l'ouverture d'une carte

### ISSUE THREAD

**Issue by djaccard** [Heigvd/colab#344]
après le zoom sur "context and objectives", j'ai voulu ouvrir la carte learning goals

<img width="1312" alt="Capture d’écran 2022-09-08 à 08 54 13" src="https://user-images.githubusercontent.com/1556490/189055146-3879462b-9310-4e1e-ac97-98aacaeaf6ed.png">

**Comment by SandraMonnier** [comment]
Caused by: java.io.InvalidClassException: ch.colabproject.colab.api.microchanges.model.MicroChange; local class incompatible: stream classdesc serialVersionUID = 7857329650355922676, local class serialVersionUID = -5414695529039855157

**Comment by SandraMonnier** [comment]
Tentative de correction en assignant un serialVersionUID défini.

**Comment by SandraMonnier** [comment]
stack trace



ERROR: 08:16:20.358 [http-thread-pool::https-listener(19)] c.c.c.a.r.u.e.AbstractExceptionMapper - Unknown Internal Error
--
Thu, Sep 8 2022 10:16:20 am | com.hazelcast.nio.serialization.HazelcastSerializationException: java.io.InvalidClassException: ch.colabproject.colab.api.microchanges.model.MicroChange; local class incompatible: stream classdesc serialVersionUID = 7857329650355922676, local class serialVersionUID = -5414695529039855157
Thu, Sep 8 2022 10:16:20 am | at com.hazelcast.internal.serialization.impl.SerializationUtil.handleException(SerializationUtil.java:103)
Thu, Sep 8 2022 10:16:20 am | at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:214)
Thu, Sep 8 2022 10:16:20 am | at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:144)
Thu, Sep 8 2022 10:16:20 am | at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrowIfException(InvocationFuture.java:99)
Thu, Sep 8 2022 10:16:20 am | at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:617)
Thu, Sep 8 2022 10:16:20 am | at com.hazelcast.cache.impl.CacheProxy.get(CacheProxy.java:486)
Thu, Sep 8 2022 10:16:20 am | at com.hazelcast.cache.impl.CacheProxy.get(CacheProxy.java:104)
Thu, Sep 8 2022 10:16:20 am | at ch.colabproject.colab.api.microchanges.live.LiveManager.getPendingChanges(LiveManager.java:204)
Thu, Sep 8 2022 10:16:20 am | at jdk.internal.reflect.GeneratedMethodAccessor397.invoke(Unknown Source)
Thu, Sep 8 2022 10:16:20 am | at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
Thu, Sep 8 2022 10:16:20 am | at java.base/java.lang.reflect.Method.invoke(Unknown Source)
Thu, Sep 8 2022 10:16:20 am | at org.glassfish.ejb.security.application.EJBSecurityManager.runMethod(EJBSecurityManager.java:588)
Thu, Sep 8 2022 10:16:20 am | at org.glassfish.ejb.security.application.EJBSecurityManager.invoke(EJBSecurityManager.java:408)
Thu, Sep 8 2022 10:16:20 am | at com.sun.ejb.containers.BaseContainer.invokeBeanMethod(BaseContainer.java:4835)
Thu, Sep 8 2022 10:16:20 am | at com.sun.ejb.EjbInvocation.invokeBeanMethod(EjbInvocation.java:665)
Thu, Sep 8 2022 10:16:20 am | at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:834)
Thu, Sep 8 2022 10:16:20 am | at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:615)
Thu, Sep 8 2022 10:16:20 am | at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.doCall(SystemInterceptorProxy.java:163)
Thu, Sep 8 2022 10:16:20 am | at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.aroundInvoke(SystemInterceptorProxy.java:140)
Thu, Sep 8 2022 10:16:20 am | at jdk.internal.reflect.GeneratedMethodAccessor175.invoke(Unknown Source)
Thu, Sep 8 2022 10:16:20 am | at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
Thu, Sep 8 2022 10:16:20 am | at java.base/java.lang.reflect.Method.invoke(Unknown Source)
Thu, Sep 8 2022 10:16:20 am | at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:888)
Thu, Sep 8 2022 10:16:20 am | at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:833)
Thu, Sep 8 2022 10:16:20 am | at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:615)
Thu, Sep 8 2022 10:16:20 am | at org.jboss.weld.module.ejb.AbstractEJBRequestScopeActivationInterceptor.aroundInvoke(AbstractEJBRequestScopeActivationInterceptor.java:72)
Thu, Sep 8 2022 10:16:20 am | at org.jboss.weld.module.ejb.SessionBeanInterceptor.aroundInvoke(SessionBeanInterceptor.java:52)
Thu, Sep 8 2022 10:16:20 am | at jdk.internal.reflect.GeneratedMethodAccessor174.invoke(Unknown Source)
Thu, Sep 8 2022 10:16:20 am | at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
Thu, Sep 8 2022 10:16:20 am | at java.base/java.lang.reflect.Method.invoke(Unknown Source)
Thu, Sep 8 2022 10:16:20 am | at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:888)
Thu, Sep 8 2022 10:16:20 am | at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:833)
Thu, Sep 8 2022 10:16:20 am | at com.sun.ejb.containers.interceptors.InterceptorManager.intercept(InterceptorManager.java:375)
Thu, Sep 8 2022 10:16:20 am | at com.sun.ejb.containers.BaseContainer.__intercept(BaseContainer.java:4807)
Thu, Sep 8 2022 10:16:20 am | at com.sun.ejb.containers.BaseContainer.intercept(BaseContainer.java:4795)
Thu, Sep 8 2022 10:16:20 am | at com.sun.ejb.containers.EJBLocalObjectInvocationHandler.invoke(EJBLocalObjectInvocationHandler.java:212)
Thu, Sep 8 2022 10:16:20 am | at com.sun.ejb.containers.EJBLocalObjectInvocationHandlerDelegate.invoke(EJBLocalObjectInvocationHandlerDelegate.java:90)
Thu, Sep 8 2022 10:16:20 am | at com.sun.proxy.$Proxy311.getPendingChanges(Unknown Source)
Thu, Sep 8 2022 10:16:20 am | at ch.colabproject.colab.api.microchanges.live.__EJB31_Generated__LiveManager__Intf____Bean__.getPendingChanges(Unknown Source)
Thu, Sep 8 2022 10:16:20 am | at jdk.internal.reflect.GeneratedMethodAccessor396.invoke(Unknown Source)
Thu, Sep 8 2022 10:16:20 am | at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
Thu, Sep 8 2022 10:16:20 am | at java.base/java.lang.reflect.Method.invoke(Unknown Source)
Thu, Sep 8 2022 10:16:20 am | at org.jboss.weld.util.reflection.Reflections.invokeAndUnwrap(Reflections.java:410)
Thu, Sep 8 2022 10:16:20 am | at org.jboss.weld.module.ejb.EnterpriseBeanProxyMethodHandler.invoke(EnterpriseBeanProxyMethodHandler.java:134)
Thu, Sep 8 2022 10:16:20 am | at org.jboss.weld.bean.proxy.EnterpriseTargetBeanInstance.invoke(EnterpriseTargetBeanInstance.java:56)
Thu, Sep 8 2022 10:16:20 am | at org.jboss.weld.module.ejb.InjectionPointPropagatingEnterpriseTargetBeanInstance.invoke(InjectionPointPropagatingEnterpriseTargetBeanInstance.java:68)
Thu, Sep 8 2022 10:16:20 am | at org.jboss.weld.bean.proxy.ProxyMethodHandler.invoke(ProxyMethodHandler.java:106)
Thu, Sep 8 2022 10:16:20 am | at ch.colabproject.colab.api.microchanges.live.LiveManager$Proxy$_$_Weld$EnterpriseProxy$.getPendingChanges(Unknown Source)
Thu, Sep 8 2022 10:16:20 am | at ch.colabproject.colab.api.rest.document.ChangeRestEndpoint.getChanges(ChangeRestEndpoint.java:53)
Thu, Sep 8 2022 10:16:20 am | at jdk.internal.reflect.GeneratedMethodAccessor395.invoke(Unknown Source)
Thu, Sep 8 2022 10:16:20 am | at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
Thu, Sep 8 2022 10:16:20 am | at java.base/java.lang.reflect.Method.invoke(Unknown Source)
Thu, Sep 8 2022 10:16:20 am | at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
Thu, Sep 8 2022 10:16:20 am | at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124)
Thu, Sep 8 2022 10:16:20 am | at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167)
Thu, Sep 8 2022 10:16:20 am | at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:219)
Thu, Sep 8 2022 10:16:20 am | at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79)
Thu, Sep 8 2022 10:16:20 am | at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:475)
Thu, Sep 8 2022 10:16:20 am | at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:397)
Thu, Sep 8 2022 10:16:20 am | at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:81)
Thu, Sep 8 2022 10:16:20 am | at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:255)
Thu, Sep 8 2022 10:16:20 am | at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
Thu, Sep 8 2022 10:16:20 am | at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
Thu, Sep 8 2022 10:16:20 am | at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
Thu, Sep 8 2022 10:16:20 am | at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
Thu, Sep 8 2022 10:16:20 am | at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
Thu, Sep 8 2022 10:16:20 am | at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
Thu, Sep 8 2022 10:16:20 am | at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:234)
Thu, Sep 8 2022 10:16:20 am | at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680)
Thu, Sep 8 2022 10:16:20 am | at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394)
Thu, Sep 8 2022 10:16:20 am | at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)
Thu, Sep 8 2022 10:16:20 am | at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:366)
Thu, Sep 8 2022 10:16:20 am | at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:319)
Thu, Sep 8 2022 10:16:20 am | at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)
Thu, Sep 8 2022 10:16:20 am | at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1637)
Thu, Sep 8 2022 10:16:20 am | at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:331)
Thu, Sep 8 2022 10:16:20 am | at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:211)
Thu, Sep 8 2022 10:16:20 am | at org.glassfish.tyrus.servlet.TyrusServletFilter.doFilter(TyrusServletFilter.java:282)
Thu, Sep 8 2022 10:16:20 am | at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:253)
Thu, Sep 8 2022 10:16:20 am | at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:211)
Thu, Sep 8 2022 10:16:20 am | at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:257)
Thu, Sep 8 2022 10:16:20 am | at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:160)
Thu, Sep 8 2022 10:16:20 am | at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:757)
Thu, Sep 8 2022 10:16:20 am | at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:577)
Thu, Sep 8 2022 10:16:20 am | at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:99)
Thu, Sep 8 2022 10:16:20 am | at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:158)
Thu, Sep 8 2022 10:16:20 am | at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:372)
Thu, Sep 8 2022 10:16:20 am | at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:239)
Thu, Sep 8 2022 10:16:20 am | at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:520)
Thu, Sep 8 2022 10:16:20 am | at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:217)
Thu, Sep 8 2022 10:16:20 am | at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:182)
Thu, Sep 8 2022 10:16:20 am | at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:156)
Thu, Sep 8 2022 10:16:20 am | at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:201)
Thu, Sep 8 2022 10:16:20 am | at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:95)
Thu, Sep 8 2022 10:16:20 am | at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:260)
Thu, Sep 8 2022 10:16:20 am | at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:177)
Thu, Sep 8 2022 10:16:20 am | at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:109)
Thu, Sep 8 2022 10:16:20 am | at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:88)
Thu, Sep 8 2022 10:16:20 am | at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:53)
Thu, Sep 8 2022 10:16:20 am | at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:524)
Thu, Sep 8 2022 10:16:20 am | at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:89)
Thu, Sep 8 2022 10:16:20 am | at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:94)
Thu, Sep 8 2022 10:16:20 am | at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:33)
Thu, Sep 8 2022 10:16:20 am | at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:114)
Thu, Sep 8 2022 10:16:20 am | at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569)
Thu, Sep 8 2022 10:16:20 am | at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549)
Thu, Sep 8 2022 10:16:20 am | at java.base/java.lang.Thread.run(Unknown Source)
Thu, Sep 8 2022 10:16:20 am | Caused by: java.io.InvalidClassException: ch.colabproject.colab.api.microchanges.model.MicroChange; local class incompatible: stream classdesc serialVersionUID = 7857329650355922676, local class serialVersionUID = -5414695529039855157
Thu, Sep 8 2022 10:16:20 am | at java.base/java.io.ObjectStreamClass.initNonProxy(Unknown Source)
Thu, Sep 8 2022 10:16:20 am | at java.base/java.io.ObjectInputStream.readNonProxyDesc(Unknown Source)
Thu, Sep 8 2022 10:16:20 am | at java.base/java.io.ObjectInputStream.readClassDesc(Unknown Source)
Thu, Sep 8 2022 10:16:20 am | at java.base/java.io.ObjectInputStream.readOrdinaryObject(Unknown Source)
Thu, Sep 8 2022 10:16:20 am | at java.base/java.io.ObjectInputStream.readObject0(Unknown Source)
Thu, Sep 8 2022 10:16:20 am | at java.base/java.io.ObjectInputStream.readObject(Unknown Source)
Thu, Sep 8 2022 10:16:20 am | at java.base/java.io.ObjectInputStream.readObject(Unknown Source)
Thu, Sep 8 2022 10:16:20 am | at java.base/java.util.ArrayList.readObject(Unknown Source)
Thu, Sep 8 2022 10:16:20 am | at java.base/jdk.internal.reflect.GeneratedMethodAccessor185.invoke(Unknown Source)
Thu, Sep 8 2022 10:16:20 am | at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
Thu, Sep 8 2022 10:16:20 am | at java.base/java.lang.reflect.Method.invoke(Unknown Source)
Thu, Sep 8 2022 10:16:20 am | at java.base/java.io.ObjectStreamClass.invokeReadObject(Unknown Source)
Thu, Sep 8 2022 10:16:20 am | at java.base/java.io.ObjectInputStream.readSerialData(Unknown Source)
Thu, Sep 8 2022 10:16:20 am | at java.base/java.io.ObjectInputStream.readOrdinaryObject(Unknown Source)
Thu, Sep 8 2022 10:16:20 am | at java.base/java.io.ObjectInputStream.readObject0(Unknown Source)
Thu, Sep 8 2022 10:16:20 am | at java.base/java.io.ObjectInputStream.defaultReadFields(Unknown Source)
Thu, Sep 8 2022 10:16:20 am | at java.base/java.io.ObjectInputStream.readSerialData(Unknown Source)
Thu, Sep 8 2022 10:16:20 am | at java.base/java.io.ObjectInputStream.readOrdinaryObject(Unknown Source)
Thu, Sep 8 2022 10:16:20 am | at java.base/java.io.ObjectInputStream.readObject0(Unknown Source)
Thu, Sep 8 2022 10:16:20 am | at java.base/java.io.ObjectInputStream.readObject(Unknown Source)
Thu, Sep 8 2022 10:16:20 am | at java.base/java.io.ObjectInputStream.readObject(Unknown Source)
Thu, Sep 8 2022 10:16:20 am | at java.base/java.util.ArrayList.readObject(Unknown Source)
Thu, Sep 8 2022 10:16:20 am | at java.base/jdk.internal.reflect.GeneratedMethodAccessor185.invoke(Unknown Source)
Thu, Sep 8 2022 10:16:20 am | at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
Thu, Sep 8 2022 10:16:20 am | at java.base/java.lang.reflect.Method.invoke(Unknown Source)
Thu, Sep 8 2022 10:16:20 am | at java.base/java.io.ObjectStreamClass.invokeReadObject(Unknown Source)
Thu, Sep 8 2022 10:16:20 am | at java.base/java.io.ObjectInputStream.readSerialData(Unknown Source)
Thu, Sep 8 2022 10:16:20 am | at java.base/java.io.ObjectInputStream.readOrdinaryObject(Unknown Source)
Thu, Sep 8 2022 10:16:20 am | at java.base/java.io.ObjectInputStream.readObject0(Unknown Source)
Thu, Sep 8 2022 10:16:20 am | at java.base/java.io.ObjectInputStream.defaultReadFields(Unknown Source)
Thu, Sep 8 2022 10:16:20 am | at java.base/java.io.ObjectInputStream.readSerialData(Unknown Source)
Thu, Sep 8 2022 10:16:20 am | at java.base/java.io.ObjectInputStream.readOrdinaryObject(Unknown Source)
Thu, Sep 8 2022 10:16:20 am | at java.base/java.io.ObjectInputStream.readObject0(Unknown Source)
Thu, Sep 8 2022 10:16:20 am | at java.base/java.io.ObjectInputStream.readObject(Unknown Source)
Thu, Sep 8 2022 10:16:20 am | at java.base/java.io.ObjectInputStream.readObject(Unknown Source)
Thu, Sep 8 2022 10:16:20 am | at com.hazelcast.internal.serialization.impl.defaultserializers.JavaDefaultSerializers$JavaSerializer.read(JavaDefaultSerializers.java:86)
Thu, Sep 8 2022 10:16:20 am | at com.hazelcast.internal.serialization.impl.defaultserializers.JavaDefaultSerializers$JavaSerializer.read(JavaDefaultSerializers.java:79)
Thu, Sep 8 2022 10:16:20 am | at fish.payara.nucleus.hazelcast.PayaraHazelcastSerializer.read(PayaraHazelcastSerializer.java:84)
Thu, Sep 8 2022 10:16:20 am | at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:44)
Thu, Sep 8 2022 10:16:20 am | at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:208)
Thu, Sep 8 2022 10:16:20 am | ... 105 common frames omitted
